# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
