# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annonces', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annonce',
            name='code_postal',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='annonce',
            name='ville',
            field=models.CharField(default='', max_length=20),
        ),
    ]
