# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_annonce_auteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='code_postal',
            field=models.IntegerField(default=77420),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='numero',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pays',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(default='Île-de-France', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rue',
            field=models.CharField(default='Allée de la Noiseraie', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ville',
            field=models.CharField(default='Noisy-le-Grand', max_length=100),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
