# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0007_auto_20161209_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(default=48.8411),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='long',
            field=models.FloatField(default=2.588),
        ),
    ]
