# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0008_auto_20161209_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='adresse',
        ),
        migrations.AddField(
            model_name='annonce',
            name='lat',
            field=models.FloatField(default=48.8411),
        ),
        migrations.AddField(
            model_name='annonce',
            name='long',
            field=models.FloatField(default=2.588),
        ),
        migrations.AddField(
            model_name='annonce',
            name='numero',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='annonce',
            name='pays',
            field=models.CharField(default='France', max_length=100),
        ),
        migrations.AddField(
            model_name='annonce',
            name='region',
            field=models.CharField(default='Île-de-France', max_length=100),
        ),
        migrations.AddField(
            model_name='annonce',
            name='rue',
            field=models.CharField(default='Allée de la Noiseraie', max_length=100),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='code_postal',
            field=models.IntegerField(default=77420),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='ville',
            field=models.CharField(default='Noisy-le-Grand', max_length=100),
        ),
    ]
