# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0009_auto_20161215_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.UserProfile'),
        ),
    ]
