# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0012_auto_20161227_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='nb_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annonce',
            name='somme_notes',
            field=models.IntegerField(default=0),
        ),
    ]
